<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

##Here comes the HTML meta tags definitions
$config['invite_friends_page_title_meta_tag'] = '{user_first_name_last_name_or_company_name} | invite_friends_page_title Pozvání & Partnerský program';
$config['invite_friends_page_description_meta_tag'] = '{user_first_name_last_name_or_company_name} | invite_friends_page_DESCRIPTION Pozvání & Partnerský';

################ URL Name Definition - start here
$config['invite_friends_page_url'] = 'invite-friends';

$config['invite_friends_send_invitations_btn_txt'] = 'EN Odeslat pozvání';

$config['copy_invite_friends_referral_link_tooltip_message_copied'] = 'Copied!';

//$config['invite_your_friends_txt'] = 'Invite Your Friends!';
$config['invite_your_friends_txt'] = 'EN Pozvání & Partnerský program';

################################# Sharing of referral url on social medias
$config['user_referral_url_facebook_share_title_short'] = "Připojte se na revoluční vlnu flexibilního a efektivního způsobu práce!";

$config['user_referral_url_facebook_share_message'] = "EN - Zrychlete a podpořte svůj růst. Hledat, vybírat a kontaktovat odborníky z celé ČR. Vytvořte si profil, prezentujte se nejlepším možným způsobem.";
$config['facebook_share_image_path'] = 'assets/images/invite_friends/fb_invite_friends.png';

$config['user_referral_url_twitter_share_message'] = "EN - Připojte se na revoluční vlnu flexibilního a efektivního způsobu práce! Klikněte zde a připojte se {referral_url}";
$config['linkedin_share_image_path'] = 'assets/images/invite_friends/ln_invite_friends.png';

$config['user_referral_url_linkedin_share_title_short'] = "Připojte se na revoluční vlnu flexibilního a efektivního způsobu práce!";

$config['user_referral_url_linkedin_share_message'] = 'Zrychlete a podpořte svůj růst. Hledat, vybírat a kontaktovat odborníky z celé ČR. Vytvořte si profil, prezentujte se nejlepším možným způsobem.';

################################
$config['invite_friends_referral_sources_statistics_facebook_lbl'] = 'Facebook';
$config['invite_friends_referral_sources_statistics_linkedin_lbl'] = 'LinkedIn';
$config['invite_friends_referral_sources_statistics_twitter_lbl'] = 'Twitter';
$config['invite_friends_referral_sources_statistics_email_lbl'] = 'Email';
$config['invite_friends_referral_sources_statistics_url_lbl'] = 'URL';
$config['invite_friends_referral_sources_statistics_code_lbl'] = 'Kód';
$config['invite_friends_referral_sources_statistics_lbl'] = 'Refferal Sources Statistics';

$config['send_invite_friends_request_popup_label_txt'] = "Pokračováním souhlasíte s odesláním pozvání pro: {invited_friends_email}.";

$config['send_invite_friends_request_sent_confirmation_msg'] = 'Your request has been successfully submitted for delivery. full overview you can find in your "activity log" and "invite friends" sections.';

$config['invite_friends_txt'] = 'Invite Friends';

// Disclaimer message
$config['free_membership_subscriber_disclaimer_message_without_downgrade_plan_history_lvl2_referral_statistics_registrations_tab'] = 'You are not eligible of earnings generated by your lvl2 network. <a href="{membership_page_url}" target="_blank">Manage your membership now...</a> (registrations tab)';

$config['free_membership_subscriber_disclaimer_message_without_downgrade_plan_history_lvl2_referral_statistics_earnings_tab'] = 'You are not eligible of earnings generated by your lvl2 network. <a href="{membership_page_url}" target="_blank">Manage your membership now...</a> (earnings tab)';

$config['free_membership_subscriber_disclaimer_message_when_downgrade_plan_history_lvl2_referral_statistics_registrations_tab'] = 'You downgraded to free mebership on {membership_downgrade_date}. Starting this date you are not eligible anymore of earnings generated by your lvl2 network. (registrations tab)';

$config['free_membership_subscriber_disclaimer_message_when_downgrade_plan_history_lvl2_referral_statistics_earnings_tab'] = 'You downgraded to free mebership on {membership_downgrade_date}. Starting this date you are not eligible anymore of earnings generated by your lvl2 network. (earnings tab)';

// This will be used for referral statistics section
$config['referral_statistics_heading'] = 'Your Referral Statistics';

$config['invite_friends_registrations_referrals_statistics_lbl'] = 'Registrations';

$config['invite_friends_earnings_referrals_statistics_lbl'] = 'Earnings';

$config['invite_friends_by_day_referrals_statistics_lbl'] = 'By Day';

$config['invite_friends_by_week_referrals_statistics_lbl'] = 'By Week';

$config['invite_friends_by_month_referrals_statistics_lbl'] = 'By Month';

$config['lvl1_referral_statistics_lbl'] = 'Level1 Referral Statistics';

$config['lvl2_referral_statistics_lbl'] = 'Level2 Referral Statistics';

$config['referral_statistics_all_time_lbl'] = 'All-time';

$config['referral_statistics_today_lbl'] = 'Today';

$config['referral_statistics_this_week_lbl'] = 'This week';

$config['referral_statistics_this_month_lbl'] = 'This Month';


// This will be used for referral statistics in charts section
$config['lvl1_registrations_day_chart_y_axis_label'] = 'DAY Y Lvl affiliate registrations (per day)';
$config['lvl1_registrations_day_chart_data_label'] = 'DAY X Level 1 Registrations';

$config['lvl1_earnings_day_chart_y_axis_label'] = 'DAY Y Lvl 1 affiliate earnings (per day)';
$config['lvl1_earnings_day_chart_data_label'] = 'DAY X Level 1 Earnings';


$config['lvl1_registrations_week_chart_y_axis_label'] = 'WEEK Y Lvl 1 affiliate registrations (per week)';
$config['lvl1_registrations_week_chart_data_label'] = 'WEEEK X Level 1 Registrations';

$config['lvl1_earnings_week_chart_y_axis_label'] = 'WEEK Y Lvl 1 affiliate earnings (per week)';
$config['lvl1_earnings_week_chart_data_label'] = 'WEEK X Level 1 Earnings';


$config['lvl1_registrations_month_chart_y_axis_label'] = 'MONTH Y Lvl 1 affiliate registrations (per month)';
$config['lvl1_registrations_month_chart_data_label'] = 'MONTH X Level 1 Registrations';

$config['lvl1_earnings_month_chart_y_axis_label'] = 'MONTH Y Lvl 1 affiliate earnings (per month)';
$config['lvl1_earnings_month_chart_data_label'] = 'MONTH X Level 1 Earnings';

####################################################################

$config['lvl2_registrations_day_chart_y_axis_label'] = 'DAY Y Lvl 2 affiliate registrations (per day)';
$config['lvl2_registrations_day_chart_data_label'] = 'DAY X Level 2 Registrations';

$config['lvl2_earnings_day_chart_y_axis_label'] = 'DAY Y Lvl 2 affiliate earnings (per day)';
$config['lvl2_earnings_day_chart_data_label'] = 'DAY X Level 2 Earnings';

$config['lvl2_registrations_week_chart_y_axis_label'] = 'WEEK Y Lvl 2 affiliate registrations (per week)';
$config['lvl2_registrations_week_chart_data_label'] = 'WEEK X Level 2 Registrations';

$config['lvl2_earnings_week_chart_y_axis_label'] = 'WEEK Y Lvl 2 affiliate earnings (per week)';
$config['lvl2_earnings_week_chart_data_label'] = 'WEEK X Level 2 Earnings';

$config['lvl2_registrations_month_chart_y_axis_label'] = 'MONTH Y Lvl 2 affiliate registrations (per month)';
$config['lvl2_registrations_month_chart_data_label'] = 'MONTH X Level 2 Registrations';

$config['lvl2_earnings_month_chart_y_axis_label'] = 'MONTH Y Lvl 2 affiliate earnings (per month)';
$config['lvl2_earnings_month_chart_data_label'] = 'MONTH X Level 2 Earnings';

#################################################################################################################

// This will be used for manage email invitations section
$config['manage_email_invitations_heading'] = 'Manage Email Invitations';

$config['tab_pending_invitation'] = 'Pending Invitations';

$config['tab_accepted_invitation'] = 'Accepted Invitations';

$config['tab_revoked_invitation'] = 'Revoked Invitations';

$config['sent_on_lbl'] = 'Sent on';

$config['accepted_on_lbl'] = 'Accepted on';

$config['revoked_on_lbl'] = 'Revoked on';

$config['time_left_till_next_resent_txt'] = 'Time left till next resent';

$config['pending_resend_available'] = 'You still have <span class="resend_available" data-id="{invitation_id}">{resend_available}</span> available resends left';

$config['no_pending_invitation'] = 'You have no pending invitation';

$config['no_accepted_invitation'] = 'You have no accepted invitation';

$config['no_revoked_invitation'] = 'You have no revoked invitation';

$config['revoke_invitation_btn'] = 'Revoke Invitation';

$config['resend_invitation_btn'] = 'Resend Invitation';


// These variable used in confirmation popup
$config['revoke_confirmation_btn'] = 'Revoke Invitation';
$config['resend_confirmation_btn'] = 'Resend Invitaion';

// Withdraw funds section 
$config['withdraw_referral_earnings_funds_btn'] = 'Withdraw Funds';

$config['user_referral_earnings_account_balance_lbl'] = "Account balance";

$config['withdraw_amount_greater_then_total_referral_earnings_account_balance_error_message'] = 'You can not withdraw more then total available balance';

$config['withdraw_amount_required_error_message'] = 'Amount is required';

$config['withdraw_referral_earnings_confirmation_popup_amount_lbl'] = 'Withdraw Funds - Amount';

$config['withdraw_referral_earnings_confirmation_popup_amount_tooltip_msg'] = 'Withdraw Funds';



$config['invite_friends_withdrawal_request_amount_label_txt'] = 'Withdrawal Requested Amount';

$config['invite_friends_withdrawal_request_submit_date_label_txt'] = 'Withdrawal Request Submit Date';

$config['invite_friends_withdrawal_request_status_label_txt'] = 'Request Status';

$config['invite_friends_withdrawal_request_admin_processing_date_label_txt'] = 'Withdrawal Request Admin Processing Date';

$config['invite_friends_withdrawal_request_approval_date_label_txt'] = 'Withdrawal Request Approval Date - Datum schválení';
$config['invite_friends_transaction_id_label_txt'] = 'Transaction Id';

$config['invite_friends_withdrawal_request_status_rejected_by_admin_txt'] = 'Rejected by admin';

$config['invite_friends_withdrawal_request_status_approved_by_admin_txt'] = 'Approved by admin';

$config['invite_friends_withdrawal_request_status_review_by_admin_txt'] = 'Admin Review';

##################################################################

$config['revoke_confirmation_text'] = 'Are you sure you want to revoke this invitation? Once an invitation is revoked, the action can not be reverted!';

$config['resend_confirmation_text'] = 'You are about to resend the invitation to <span class="default_popup_blue_text">{invitee_email_address}</span>.';

$config['invite_friends_user_available_resends_depleted_error_message'] = 'You can not resend invitation to this user as your available resends already expired.'; // This variable is used to display error when user available slots depleted and he try to resent invitation

$config['invite_friends_user_try_revoke_invitation_already_accepted_error_message'] = 'EN-you can not revoke. invitation already accepted';
$config['invite_friends_user_try_resend_invitation_already_revoked_error_message'] = 'EN-you can not resend. invitation already revoked';
$config['invite_friends_user_try_resend_invitation_already_accepted_error_message'] = 'EN-you can not resend. invitation already accepted';

$config['invite_friends_user_try_resend_invitation_before_next_available_time_being_available_error_message'] = 'EN-you can not resend. invitation already sent'; // This variable is used to display error when user try to resent invitation before available resend time

####################################### Activity log and realtime notification message ####################################################################################

$config['revoked_invitation_user_activity_log'] = 'You revoked invitation of email <b>"{invitee_email_address}"</b>';


$config['invite_friends_revoked_invitation_confirmation_message'] = 'Pozvání bylo zrušeno.';

$config['resend_invitation_confirmation_message'] = 'Invitation was resent successfully.';

$config['withdraw_amount_request_from_referral_earnings_user_activity_log'] = 'You requested to withdraw affiliate generated amount of {withdraw_amount} '.CURRENCY.'. Currently your request is under admin review. Once approved by admin, this amount will be transferred to your account balance.';

$config['admin_approved_withdraw_amount_request_from_referral_earnings_user_activity_log'] = 'Admin approved your withdraw request of affiliate earning {withdraw_amount} '.CURRENCY.'. the amount was transferred to your account balance.';


$config['admin_rejected_withdraw_amount_request_from_referral_earnings_user_activity_log'] = 'Admin rejected your withdraw request of affiliate earning {withdraw_amount} '.CURRENCY.'. the amount was transferred back to your affiliate earning account balance. should you have any questions about this situation, contact admin.';

$config['withdraw_amount_request_success_confirmation_message'] = 'Your withdraw request for {withdraw_amount} '.CURRENCY.' is submited for admin review.';

##################################### Activity log messages ####################################
$config['total_successfully_sent_invitations_user_activity_log_message'] = 'Total of {total} invitations has been successfully sent.';
$config['already_sent_invitation_warning_user_activity_log_message'] = '{already_sent} were failed due to already sent invitation.';
$config['invalid_email_user_activity_log_message'] = '{invalid_email} were failed due to invalid email address.';

$config['sent_invitation_to_invite_friends_email_already_registered_user_activity_log_message_1_failed_send'] = 'EN - {already_exist} odeslané pozvání nebylo úspěšné, protože použitá emailová adresa je již registrována.';

$config['sent_invitation_to_invite_friends_email_already_registered_user_activity_log_message_2_to_4_failed_sends'] = 'EN - {already_exist} odeslaná pozvání nebyly úspěšné, protože použité emailové adresy jsou již registrovány.';

$config['sent_invitation_to_invite_friends_email_already_registered_user_activity_log_message_more_or_equal_5_failed_sends'] = 'EN - {already_exist} odeslaných pozvání nebyly úspěšné, protože použité emailové adresy jsou již registrovány.';

$config['sent_yourself_invitation_user_activity_log_message'] = '{your_self} were failed because you sent to yourself.';

$config['reminder_email_invitation_sent_activity_log_message'] = 'You have sent reminder invitation to email <b>{invitee_email_address}</b>';
################################################################################################

$config['invite_friends_page_month_chart_months_names'] = [
 1 => 'January',
 2 => 'February',
 3 => 'March',
 4 => 'April',
 5 => 'May',
 6 => 'June',
 7 => 'July',
 8 => 'August',
 9 => 'September',
 10 => 'October',
 11 => 'November',
 12 => 'December'
];

?>